services:
  app:
    build: .
    container_name: rezerwuj-app
    ports:
      - "127.0.0.1:8002:8000"
    volumes:
      - rezerwuj-data:/app/data
    env_file:
      - .env.production
    environment:
      - DATABASE_URL=sqlite:///./data/rezerwuj.db
    restart: always

volumes:
  rezerwuj-data:
